# Generated by Django 5.2 on 2025-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.FileField(null=True, upload_to='materials/'),
        ),
    ]
